### PR TITLE
fix: UI not responsive

### PR DESCRIPTION
**Pull request by chinazaaa**
# Kickstart Frontend Pull Request Template

## Description

Please include a summary of the changes and the motivation behind them. Provide context for the changes, such as bug fixes, new features, or improvements.

- **What does this PR do?**

- **Why are these changes necessary?**

- **Related Issue(s)/Ticket(s):** 
  - Link to any related issues or tickets, if applicable.

## Type of Change

Please mark the options that are relevant to your PR:

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Code refactor (non-breaking change that improves code quality or structure)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update (adds or updates documentation)
- [x] 💄 UI update (changes that affect the UI/UX)

## Screenshots (if applicable)

Include screenshots or GIFs if your PR introduces visual changes. 

| Before | After |
|--------|-------|
| (Old UI
363464839-e4cf5579-8335-4a88-8a04-1413630afab6
) | (New UI
Screenshot_2024-09-03_18-18-04
) |

## Checklist

Please ensure all of these tasks are completed before requesting a review:

- [x] My code follows the project's coding style.
- [x] I have performed a self-review of my code.
- [x] I have commented my code where necessary, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [x] My changes do not introduce new warnings or errors.
- [ ] I have added tests that prove my fix is effective or that my feature works (if applicable).
- [ ] New and existing unit tests pass locally with my changes.

## How Has This Been Tested?

Please describe the tests you ran to verify your changes. Provide instructions so that reviewers can replicate the testing process.

- **Tested on:** 
  - [x] Local development environment
  - [x] Staging environment
  - [ ] Browser(s) (list the browsers you tested on)
  - [x] Mobile device (if applicable)

## Additional Context

Add any other context or information here, such as dependencies, potential impacts on other parts of the project, or notes for the reviewer.

## Reviewers

Tag the GitHub usernames of the people who should review this PR. Please ensure code owners are included if applicable.

### CODE REVIEW

**Comment by chinazaaa** [comment]
the use of the container class provided by @shadcn-ui will be of great help same goes to the cn utils added by shadcn

also migration to the Next.js Image component will optimize Image performance

**Comment by chinazaaa** [comment]
ref: https://github.com/Kickstart-in-net/frontend/issues/9#issue-2499266353

**Comment by SRINJAYDASGUPTA-Git** [comment]
Hi @chinazaaa thanks for your contribution, but there are some slight changes that we need: 
The sections when not hovered should look like this:
image
and when hovered it should be like this:
image

Some small spacing problems 🙃 

Thanks!

**Comment by chinazaaa** [comment]
Noted @SRINJAYDASGUPTA-Git 

If possible can I get a figma design I can refer to it will be of help

**Comment by SRINJAYDASGUPTA-Git** [comment]
Sure @chinazaaa here's our figma prototype:

[https://www.figma.com/proto/JmiQKAU2PaUK0x7ft7xRDW/KickStart?node-id=884-2375&t=1RvKbgnNfDmEXHO1-1&scaling=scale-down-width&content-scaling=fixed&page-id=884%3A242](Prototype)

**Comment by prabuddha369** [comment]
Thankyou @chinazaaa for contributing , but the issue was resolved , and due to inactivity this PR was closed.

**Pull request closed without merging**
