### PR TITLE
Dev/lower landing

### PR DESCRIPTION
**Pull request by soumik-github-4223**
# Kickstart Frontend Pull Request Template

## Description
Created the about component where 'Smart Contract', 'Join the future of freelancing' parts are there. 

- **What does this PR do?**

- **Why are these changes necessary?**

- **Related Issue(s)/Ticket(s):** 
  - Link to any related issues or tickets, if applicable.

## Type of Change

Please mark the options that are relevant to your PR:

- [ ] 🐛 Bug fix (non-breaking change which fixes an issue)
- [✅ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Code refactor (non-breaking change that improves code quality or structure)
- [ ] 🚨 Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] 📚 Documentation update (adds or updates documentation)
- [ ✅] 💄 UI update (changes that affect the UI/UX)

## Screenshots (if applicable)

Include screenshots or GIFs if your PR introduces visual changes. 

| Before | After |
|--------|-------|
| (Old UI) | (New UI) |

## Checklist

Please ensure all of these tasks are completed before requesting a review:

- [✅ ] My code follows the project's coding style.
- [ ✅] I have performed a self-review of my code.
- [ ✅] I have commented my code where necessary, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation (if applicable).
- [ ✅] My changes do not introduce new warnings or errors.
- [ ✅] I have added tests that prove my fix is effective or that my feature works (if applicable).
- [ ✅] New and existing unit tests pass locally with my changes.

## How Has This Been Tested?

Please describe the tests you ran to verify your changes. Provide instructions so that reviewers can replicate the testing process.

- **Tested on:** 
  - [ ] Local development environment
  - [ ] Staging environment
  - [ ] Browser(s) (list the browsers you tested on)
  - [ ] Mobile device (if applicable)

## Additional Context

Add any other context or information here, such as dependencies, potential impacts on other parts of the project, or notes for the reviewer.

## Reviewers

Tag the GitHub usernames of the people who should review this PR. Please ensure code owners are included if applicable.

### CODE REVIEW

**Review by SRINJAYDASGUPTA-Git — COMMENTED** [review]
@soumik-github-4223 Please give me a ss of the current home/landing page if you have added the upper half too. If not then please merge with @blackcat-007 's branch to see both of your components are working together and then post a pr. All in all GREAT work 👍🏼😃

**Comment by SRINJAYDASGUPTA-Git** [comment]
and one more thing @soumik-github-4223 u just give x to mark it done within the [ ] ok? it looks like a check box
`- [x] My code follows the project's coding style.`  will look like this: 
- [x] My code follows the project's coding style.

**Comment by soumik-github-4223** [comment]
Okk srinjay, understood all the things. Will follow from now on👍🏻

**Comment by SRINJAYDASGUPTA-Git** [comment]
@soumik-github-4223 So i am closing this pr. Create another one when u have merged yours and @blackcat-007 's work. ok?

@prabuddha369 opinions?

**Comment by prabuddha369** [comment]
Since you are doing frontend Changes, provide an SS of Old version of that feature or button or etc and the New version @soumik-github-4223 @blackcat-007 .

**Review by prabuddha369 — APPROVED** [review]

**Pull request closed without merging**
